version: "3.9"

services:
  backend:
    build: .
    working_dir: /app
    command: uvicorn main:app --host 0.0.0.0 --reload
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - 8008:8000
    restart: on-failure
